# Generated by Django 5.2.7 on 2025-11-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(default='blog!')),
                ('image', models.ImageField(default='D:\\Guitar', upload_to='D:\\Python_Scripts\\miniSite2\\miniSite2\\images')),
            ],
        ),
    ]
