# Generated by Django 5.2.7 on 2025-11-09 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('email', models.TextField(default='blog!')),
                ('gist', models.TextField(default='blog!')),
                ('body', models.TextField(default='blog!')),
            ],
        ),
    ]
